CREATE TABLE 'arcade_story_list' ('story_id' INTEGER NOT NULL, 'arcade_id' INTEGER NOT NULL, 'sub_title' TEXT NOT NULL, PRIMARY KEY('story_id'));
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5021700, /*arcade_id*/1003, /*sub_title*/'和香织在海边大特训！');
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5021701, /*arcade_id*/1003, /*sub_title*/'以礼而始以礼而终');
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5021710, /*arcade_id*/1003, /*sub_title*/'挑战自己的极限');
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5021711, /*arcade_id*/1003, /*sub_title*/'真的才是最好的');
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5027700, /*arcade_id*/1004, /*sub_title*/'再次前往厄尔庇斯岛！');
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5027701, /*arcade_id*/1004, /*sub_title*/'过于热血的战斗');
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5027702, /*arcade_id*/1004, /*sub_title*/'压轴登场');
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5027703, /*arcade_id*/1004, /*sub_title*/'战斗的结局……');
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5027704, /*arcade_id*/1004, /*sub_title*/'向更高处进发！');
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5040700, /*arcade_id*/1005, /*sub_title*/'看好奶酪！');
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5040701, /*arcade_id*/1005, /*sub_title*/'和弱小敌人的攻防');
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5040702, /*arcade_id*/1005, /*sub_title*/'奶酪的诱惑');
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5040703, /*arcade_id*/1005, /*sub_title*/'萌芽的爱情？');
INSERT INTO `arcade_story_list` VALUES (/*story_id*/5040704, /*arcade_id*/1005, /*sub_title*/'劳动会一直持续下去');
CREATE INDEX 'arcade_story_list_0_arcade_id' on 'arcade_story_list'('arcade_id');
