CREATE TABLE 'caravan_buddy' ('buddy_id' INTEGER NOT NULL, 'unit_id' INTEGER NOT NULL, 'name' TEXT NOT NULL, 'description' TEXT NOT NULL, 'effect_description1' TEXT NOT NULL, 'effect_description2' TEXT NOT NULL, 'effect_type' INTEGER NOT NULL, 'effect_value_1' INTEGER NOT NULL, 'effect_value_2' INTEGER NOT NULL, 'effect_turn' INTEGER NOT NULL, PRIMARY KEY('buddy_id'));
INSERT INTO `caravan_buddy` VALUES (/*buddy_id*/1001, /*unit_id*/126501, /*name*/'莱拉耶尔', /*description*/'打开最高50％折扣确定的商店（1件商品100％折扣）', /*effect_description1*/'', /*effect_description2*/'', /*effect_type*/1, /*effect_value_1*/10001, /*effect_value_2*/0, /*effect_turn*/1);
INSERT INTO `caravan_buddy` VALUES (/*buddy_id*/1002, /*unit_id*/105301, /*name*/'莫妮卡', /*description*/'最多获得1000里程', /*effect_description1*/'', /*effect_description2*/'', /*effect_type*/2, /*effect_value_1*/10001, /*effect_value_2*/0, /*effect_turn*/2);
INSERT INTO `caravan_buddy` VALUES (/*buddy_id*/1003, /*unit_id*/126401, /*name*/'克萝茜', /*description*/'获得{0}份料理', /*effect_description1*/'', /*effect_description2*/'', /*effect_type*/3, /*effect_value_1*/1, /*effect_value_2*/0, /*effect_turn*/1);
INSERT INTO `caravan_buddy` VALUES (/*buddy_id*/1004, /*unit_id*/100501, /*name*/'茉莉', /*description*/'可重掷{0}次骰子', /*effect_description1*/'可重掷{0}次骰子\n（剩余{1}次）', /*effect_description2*/'可重掷{0}次骰子\n如无法重掷，将获得里程', /*effect_type*/4, /*effect_value_1*/1, /*effect_value_2*/0, /*effect_turn*/3);
INSERT INTO `caravan_buddy` VALUES (/*buddy_id*/1005, /*unit_id*/101301, /*name*/'七七香', /*description*/'可重掷{0}次骰子', /*effect_description1*/'可重掷{0}次骰子\n（剩余{1}次）', /*effect_description2*/'可重掷{0}次骰子\n如无法重掷，将获得里程', /*effect_type*/4, /*effect_value_1*/2, /*effect_value_2*/0, /*effect_turn*/2);
INSERT INTO `caravan_buddy` VALUES (/*buddy_id*/1006, /*unit_id*/104301, /*name*/'真琴', /*description*/'同时掷点数为{0}的骰子\n然后可从中选择一个', /*effect_description1*/'同时掷点数为{0}的骰子\n然后可从中选择一个', /*effect_description2*/'', /*effect_type*/5, /*effect_value_1*/4, /*effect_value_2*/0, /*effect_turn*/2);
INSERT INTO `caravan_buddy` VALUES (/*buddy_id*/1007, /*unit_id*/102701, /*name*/'惠理子', /*description*/'同时掷点数为{0}的骰子\n然后可从中选择一个', /*effect_description1*/'同时掷点数为{0}的骰子\n然后可从中选择一个', /*effect_description2*/'', /*effect_type*/5, /*effect_value_1*/3, /*effect_value_2*/0, /*effect_turn*/3);
INSERT INTO `caravan_buddy` VALUES (/*buddy_id*/1008, /*unit_id*/100901, /*name*/'杏奈', /*description*/'在点数累计达到{0}以上之前\n都能继续掷骰子', /*effect_description1*/'在点数累计达到{0}以上之前\n都能继续掷骰子', /*effect_description2*/'', /*effect_type*/6, /*effect_value_1*/7, /*effect_value_2*/0, /*effect_turn*/1);
