CREATE TABLE 'custom_mypage_group' ('group_id' INTEGER NOT NULL, 'group_name' TEXT NOT NULL, PRIMARY KEY('group_id'));
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/10001, /*group_name*/'公主连结！Re:Dive 1');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/10002, /*group_name*/'公主连结！Re:Dive 2');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/10003, /*group_name*/'公主连结！Re:Dive 3');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/10004, /*group_name*/'公主连结！Re:Dive 4');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/10005, /*group_name*/'公主连结！Re:Dive 第2季 1');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/10006, /*group_name*/'公主连结！Re:Dive 第2季 2');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/10007, /*group_name*/'公主连结！Re:Dive 第2季 3');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/10008, /*group_name*/'公主连结！Re:Dive 第2季 全卷购买特典');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/10009, /*group_name*/'CD购买特典');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/20001, /*group_name*/'公主连结！Re:Dive 3周年纪念');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/20002, /*group_name*/'官方插画 第3卷 发售纪念道具');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/20003, /*group_name*/'公主连结！Re:Dive 3.5周年纪念');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/20004, /*group_name*/'公主连结！Re:Dive 4周年纪念');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/20005, /*group_name*/'公主连结！Re:Dive 4.5周年纪念');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/20006, /*group_name*/'公主连结！Re:Dive 5周年纪念');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/20007, /*group_name*/'公主连结！Re：Dive 6周年纪念');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/29906, /*group_name*/'公主连结！Re:Dive 简中服5周年特别纪念');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/30001, /*group_name*/'小游戏·迷你内容');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/40001, /*group_name*/'大家的日历');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/40002, /*group_name*/'罗森联动纪念');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/40003, /*group_name*/'百利达联动纪念');
INSERT INTO `custom_mypage_group` VALUES (/*group_id*/40004, /*group_name*/'2024年情人节纪念');
