CREATE TABLE 'event_gacha_data' ('gacha_id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'gacha_name' TEXT NOT NULL, 'item_type' INTEGER NOT NULL, 'item_id' INTEGER NOT NULL, 'cost' INTEGER NOT NULL, 'repeat_step' INTEGER NOT NULL, PRIMARY KEY('gacha_id'));
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10001, /*event_id*/10001, /*gacha_name*/'初音盒子扭蛋', /*item_type*/2, /*item_id*/60002, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10002, /*event_id*/10002, /*gacha_name*/'小小甜心冒险家讨伐证交换', /*item_type*/2, /*item_id*/60012, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10004, /*event_id*/10004, /*gacha_name*/'危险假日！海边的美食家公主', /*item_type*/2, /*item_id*/60032, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10005, /*event_id*/10005, /*gacha_name*/'珠希与美冬的无人岛0金币生活', /*item_type*/2, /*item_id*/60042, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10006, /*event_id*/10006, /*gacha_name*/'黑铁的亡灵', /*item_type*/2, /*item_id*/60052, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10007, /*event_id*/10007, /*gacha_name*/'不给布丁就捣蛋！约定的万圣节派对', /*item_type*/2, /*item_id*/60062, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10008, /*event_id*/10008, /*gacha_name*/'暮光破坏者', /*item_type*/2, /*item_id*/60072, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10009, /*event_id*/10009, /*gacha_name*/'忘却的圣歌', /*item_type*/2, /*item_id*/60082, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10010, /*event_id*/10010, /*gacha_name*/'新春破晓之星大危机', /*item_type*/2, /*item_id*/60092, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10011, /*event_id*/10011, /*gacha_name*/'情人节之战！正中红心的甜蜜战斗', /*item_type*/2, /*item_id*/60102, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10012, /*event_id*/10012, /*gacha_name*/'王都的名侦探　叹息的追踪者（STALKER）', /*item_type*/2, /*item_id*/60112, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10013, /*event_id*/10013, /*gacha_name*/'盛开在阿斯特朗的双轮之花', /*item_type*/2, /*item_id*/60122, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10014, /*event_id*/10014, /*gacha_name*/'复刻初音的礼物大作战', /*item_type*/2, /*item_id*/60132, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10015, /*event_id*/10015, /*gacha_name*/'将军道中记　白翼的武士', /*item_type*/2, /*item_id*/60142, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10016, /*event_id*/10016, /*gacha_name*/'复刻小小甜心冒险家', /*item_type*/2, /*item_id*/60152, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10017, /*event_id*/10017, /*gacha_name*/'Re: 从零开始收集的异世界餐桌', /*item_type*/2, /*item_id*/60162, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10018, /*event_id*/10018, /*gacha_name*/'复刻吸血鬼猎人with伊莉亚', /*item_type*/2, /*item_id*/60172, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10019, /*event_id*/10019, /*gacha_name*/'铃奈的RAINBOW STAGE！', /*item_type*/2, /*item_id*/60182, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10020, /*event_id*/10020, /*gacha_name*/'复刻危险假日！海边的美食家公主', /*item_type*/2, /*item_id*/60192, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10021, /*event_id*/10021, /*gacha_name*/'盛夏的真步真步王国 海滩上的灵魂之夏！', /*item_type*/2, /*item_id*/60202, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10022, /*event_id*/10022, /*gacha_name*/'珠希与美冬的无人岛0金币生活', /*item_type*/2, /*item_id*/60212, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/19003, /*event_id*/10003, /*gacha_name*/'吸血鬼猎人with伊莉亚讨伐证交换', /*item_type*/2, /*item_id*/60022, /*cost*/1, /*repeat_step*/5);
