CREATE TABLE 'gacha_exchange_lineup' ('id' INTEGER NOT NULL, 'exchange_id' INTEGER NOT NULL, 'unit_id' INTEGER NOT NULL, 'rarity' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `gacha_exchange_lineup` VALUES (/*id*/1, /*exchange_id*/1, /*unit_id*/104701, /*rarity*/3);
INSERT INTO `gacha_exchange_lineup` VALUES (/*id*/2, /*exchange_id*/2, /*unit_id*/101001, /*rarity*/3);
INSERT INTO `gacha_exchange_lineup` VALUES (/*id*/3, /*exchange_id*/2, /*unit_id*/104301, /*rarity*/3);
INSERT INTO `gacha_exchange_lineup` VALUES (/*id*/4, /*exchange_id*/3, /*unit_id*/106301, /*rarity*/3);
INSERT INTO `gacha_exchange_lineup` VALUES (/*id*/5, /*exchange_id*/4, /*unit_id*/102801, /*rarity*/3);
INSERT INTO `gacha_exchange_lineup` VALUES (/*id*/6, /*exchange_id*/5, /*unit_id*/103601, /*rarity*/3);
INSERT INTO `gacha_exchange_lineup` VALUES (/*id*/7, /*exchange_id*/6, /*unit_id*/101201, /*rarity*/3);
INSERT INTO `gacha_exchange_lineup` VALUES (/*id*/8, /*exchange_id*/7, /*unit_id*/104401, /*rarity*/3);
INSERT INTO `gacha_exchange_lineup` VALUES (/*id*/9, /*exchange_id*/8, /*unit_id*/102901, /*rarity*/3);
INSERT INTO `gacha_exchange_lineup` VALUES (/*id*/10, /*exchange_id*/9, /*unit_id*/107501, /*rarity*/3);
INSERT INTO `gacha_exchange_lineup` VALUES (/*id*/11, /*exchange_id*/10, /*unit_id*/107701, /*rarity*/3);
INSERT INTO `gacha_exchange_lineup` VALUES (/*id*/12, /*exchange_id*/11, /*unit_id*/107801, /*rarity*/3);
