CREATE TABLE 'tpr_story_data' ('sub_story_id' INTEGER NOT NULL, 'original_event_id' INTEGER NOT NULL, 'title' TEXT NOT NULL, 'condition_panel_id' INTEGER NOT NULL, 'reward_type' INTEGER NOT NULL, 'reward_id' INTEGER NOT NULL, 'reward_count' INTEGER NOT NULL, PRIMARY KEY('sub_story_id'));
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148061, /*original_event_id*/10148, /*title*/'快速吃甜食俱乐部', /*condition_panel_id*/1, /*reward_type*/8, /*reward_id*/91002, /*reward_count*/40);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148062, /*original_event_id*/10148, /*title*/'潘坡克林的真面目？', /*condition_panel_id*/1, /*reward_type*/0, /*reward_id*/0, /*reward_count*/0);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148064, /*original_event_id*/10148, /*title*/'风平浪静夜晚的恋爱话题？', /*condition_panel_id*/2, /*reward_type*/8, /*reward_id*/91002, /*reward_count*/40);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148065, /*original_event_id*/10148, /*title*/'麦酒、绑架和推理', /*condition_panel_id*/2, /*reward_type*/0, /*reward_id*/0, /*reward_count*/0);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148067, /*original_event_id*/10148, /*title*/'在亮闪闪的冲浪板上', /*condition_panel_id*/3, /*reward_type*/8, /*reward_id*/91002, /*reward_count*/40);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148068, /*original_event_id*/10148, /*title*/'受虐狂是什么？', /*condition_panel_id*/3, /*reward_type*/0, /*reward_id*/0, /*reward_count*/0);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148070, /*original_event_id*/10148, /*title*/'西瓜之后是牛奶？', /*condition_panel_id*/4, /*reward_type*/8, /*reward_id*/91002, /*reward_count*/40);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148071, /*original_event_id*/10148, /*title*/'骑士弟弟疗法', /*condition_panel_id*/4, /*reward_type*/0, /*reward_id*/0, /*reward_count*/0);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148073, /*original_event_id*/10148, /*title*/'拍拍和吹吹', /*condition_panel_id*/5, /*reward_type*/8, /*reward_id*/91002, /*reward_count*/40);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148074, /*original_event_id*/10148, /*title*/'用火遁之术做茶泡饭！', /*condition_panel_id*/5, /*reward_type*/0, /*reward_id*/0, /*reward_count*/0);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148076, /*original_event_id*/10148, /*title*/'只要侧耳倾听', /*condition_panel_id*/6, /*reward_type*/8, /*reward_id*/91002, /*reward_count*/40);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148077, /*original_event_id*/10148, /*title*/'要不还是来一次驱邪吧？', /*condition_panel_id*/6, /*reward_type*/0, /*reward_id*/0, /*reward_count*/0);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148079, /*original_event_id*/10148, /*title*/'震撼诞生的火热坠击', /*condition_panel_id*/7, /*reward_type*/8, /*reward_id*/91002, /*reward_count*/40);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148080, /*original_event_id*/10148, /*title*/'超级史莱姆战士', /*condition_panel_id*/7, /*reward_type*/0, /*reward_id*/0, /*reward_count*/0);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148601, /*original_event_id*/10148, /*title*/'零散的照片和证言', /*condition_panel_id*/0, /*reward_type*/0, /*reward_id*/0, /*reward_count*/0);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148602, /*original_event_id*/10148, /*title*/'相册修复完成！', /*condition_panel_id*/7, /*reward_type*/0, /*reward_id*/0, /*reward_count*/0);
INSERT INTO `tpr_story_data` VALUES (/*sub_story_id*/5148603, /*original_event_id*/10148, /*title*/'集体纪念照★', /*condition_panel_id*/100, /*reward_type*/0, /*reward_id*/0, /*reward_count*/0);
CREATE INDEX 'tpr_story_data_0_original_event_id' on 'tpr_story_data'('original_event_id');
