CREATE TABLE 'unique_equip_craft_enhance' ('equipment_id' INTEGER NOT NULL, 'consume_group_id' INTEGER NOT NULL, PRIMARY KEY('equipment_id'));
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130112, /*consume_group_id*/16);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130132, /*consume_group_id*/19);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130162, /*consume_group_id*/4);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130332, /*consume_group_id*/9);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130492, /*consume_group_id*/15);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130582, /*consume_group_id*/10);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130602, /*consume_group_id*/5);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130772, /*consume_group_id*/1);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130792, /*consume_group_id*/2);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130802, /*consume_group_id*/3);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130812, /*consume_group_id*/6);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130822, /*consume_group_id*/7);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130832, /*consume_group_id*/8);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130842, /*consume_group_id*/11);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130852, /*consume_group_id*/12);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130862, /*consume_group_id*/13);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130902, /*consume_group_id*/14);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130912, /*consume_group_id*/15);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130952, /*consume_group_id*/17);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/130962, /*consume_group_id*/18);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/131002, /*consume_group_id*/4);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/131012, /*consume_group_id*/21);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/131032, /*consume_group_id*/22);
INSERT INTO `unique_equip_craft_enhance` VALUES (/*equipment_id*/131072, /*consume_group_id*/20);
CREATE INDEX 'unique_equip_craft_enhance_0_consume_group_id' on 'unique_equip_craft_enhance'('consume_group_id');
