CREATE TABLE 'unit_background' ('unit_id' INTEGER NOT NULL, 'unit_name' TEXT NOT NULL, 'bg_id' INTEGER NOT NULL, 'bg_name' TEXT NOT NULL, 'position' REAL NOT NULL, 'face_type' INTEGER NOT NULL, PRIMARY KEY('unit_id'));
INSERT INTO `unit_background` VALUES (/*unit_id*/100101, /*unit_name*/'春咲日和莉', /*bg_id*/500040, /*bg_name*/'兰德索尔 公会之家', /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/100201, /*unit_name*/'草野优衣', /*bg_id*/500040, /*bg_name*/'兰德索尔 公会之家', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100301, /*unit_name*/'士条怜', /*bg_id*/500040, /*bg_name*/'兰德索尔 公会之家', /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/100401, /*unit_name*/'穗高未奏希', /*bg_id*/500140, /*bg_name*/'普莱诺平原', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100501, /*unit_name*/'织原茉莉', /*bg_id*/500090, /*bg_name*/'兰德索尔 王城入口', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100601, /*unit_name*/'风宫茜里', /*bg_id*/500260, /*bg_name*/'古城', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100701, /*unit_name*/'出云宫子', /*bg_id*/500260, /*bg_name*/'古城', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100801, /*unit_name*/'虹村雪', /*bg_id*/500140, /*bg_name*/'普莱诺平原', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100901, /*unit_name*/'柊杏奈', /*bg_id*/500050, /*bg_name*/'兰德索尔 饮食店内', /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/101001, /*unit_name*/'姬宫真步', /*bg_id*/500060, /*bg_name*/'自卫团 据点', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101101, /*unit_name*/'衣之咲璃乃', /*bg_id*/500030, /*bg_name*/'兰德索尔 繁华街', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101201, /*unit_name*/'柏崎初音', /*bg_id*/500180, /*bg_name*/'精灵之森', /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/101301, /*unit_name*/'丹野七七香', /*bg_id*/500050, /*bg_name*/'兰德索尔 饮食店内', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/101401, /*unit_name*/'雾原香澄', /*bg_id*/500060, /*bg_name*/'自卫团 据点', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101501, /*unit_name*/'爱川美里', /*bg_id*/500180, /*bg_name*/'精灵之森', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101601, /*unit_name*/'美波铃奈', /*bg_id*/500080, /*bg_name*/'月光学院', /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/101701, /*unit_name*/'喜屋武香织', /*bg_id*/500060, /*bg_name*/'自卫团 据点', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101801, /*unit_name*/'支仓伊绪', /*bg_id*/500080, /*bg_name*/'月光学院', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102001, /*unit_name*/'茜美美', /*bg_id*/500140, /*bg_name*/'普莱诺平原', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/102101, /*unit_name*/'栗林胡桃', /*bg_id*/500110, /*bg_name*/'咲恋救济院 大厅', /*position*/0.0, /*face_type*/5);
INSERT INTO `unit_background` VALUES (/*unit_id*/102201, /*unit_name*/'风宫依里', /*bg_id*/500260, /*bg_name*/'古城', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102301, /*unit_name*/'北条绫音', /*bg_id*/500110, /*bg_name*/'咲恋救济院 大厅', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102501, /*unit_name*/'天野铃莓', /*bg_id*/500110, /*bg_name*/'咲恋救济院 大厅', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102601, /*unit_name*/'森近铃', /*bg_id*/500150, /*bg_name*/'牧场 据点', /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/102701, /*unit_name*/'仓石恵理子', /*bg_id*/500050, /*bg_name*/'兰德索尔 饮食店内', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102801, /*unit_name*/'佐佐木咲恋', /*bg_id*/500110, /*bg_name*/'咲恋救济院 大厅', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102901, /*unit_name*/'樱井望', /*bg_id*/500010, /*bg_name*/'兰德索尔 市街地', /*position*/0.0, /*face_type*/1);
INSERT INTO `unit_background` VALUES (/*unit_id*/103001, /*unit_name*/'妮侬·朱柏尔', /*bg_id*/500140, /*bg_name*/'普莱诺平原', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/103101, /*unit_name*/'上喜忍', /*bg_id*/500260, /*bg_name*/'古城', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/103201, /*unit_name*/'藤堂秋乃', /*bg_id*/500070, /*bg_name*/'墨丘利财团 据点', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/103301, /*unit_name*/'野户真阳', /*bg_id*/500150, /*bg_name*/'牧场 据点', /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/103401, /*unit_name*/'绫濑由加莉', /*bg_id*/500070, /*bg_name*/'墨丘利财团 据点', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/103601, /*unit_name*/'冰川 镜华', /*bg_id*/500140, /*bg_name*/'普莱诺平原', /*position*/0.0, /*face_type*/1);
INSERT INTO `unit_background` VALUES (/*unit_id*/103701, /*unit_name*/'御久间智', /*bg_id*/500090, /*bg_name*/'王城入口', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/103801, /*unit_name*/'柏崎栞', /*bg_id*/500150, /*bg_name*/'牧场 据点', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/104001, /*unit_name*/'双叶碧', /*bg_id*/500180, /*bg_name*/'精灵之森', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/104201, /*unit_name*/'三角千歌', /*bg_id*/500010, /*bg_name*/'市街地', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/104301, /*unit_name*/'安芸真琴', /*bg_id*/500060, /*bg_name*/'自警团 据点', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/104401, /*unit_name*/'伊莉亚·奥恩斯坦', /*bg_id*/500260, /*bg_name*/'古城', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/104501, /*unit_name*/'远见空花', /*bg_id*/500140, /*bg_name*/'普莱诺平原', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/104601, /*unit_name*/'宫坂珠希', /*bg_id*/500070, /*bg_name*/'墨丘利财团 据点', /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/104701, /*unit_name*/'白银纯', /*bg_id*/500090, /*bg_name*/'兰德索尔 王城入口', /*position*/0.0, /*face_type*/1);
INSERT INTO `unit_background` VALUES (/*unit_id*/104801, /*unit_name*/'大神美冬', /*bg_id*/500070, /*bg_name*/'墨丘利财团 据点', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/104901, /*unit_name*/'星野静流', /*bg_id*/500030, /*bg_name*/'兰德索尔 繁华街', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/105001, /*unit_name*/'玉泉美咲', /*bg_id*/500080, /*bg_name*/'月光学院', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/105101, /*unit_name*/'宵滨深月', /*bg_id*/500050, /*bg_name*/'兰德索尔 饮食店内', /*position*/0.0, /*face_type*/6);
INSERT INTO `unit_background` VALUES (/*unit_id*/105201, /*unit_name*/'莉玛', /*bg_id*/500150, /*bg_name*/'牧场 据点', /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/105301, /*unit_name*/'莫妮卡·拜斯温特', /*bg_id*/500140, /*bg_name*/'普莱诺平原', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/105401, /*unit_name*/'茧宫纺希', /*bg_id*/500010, /*bg_name*/'兰德索尔 市街地', /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/105501, /*unit_name*/'石桥步美', /*bg_id*/500140, /*bg_name*/'普莱诺平原', /*position*/0.0, /*face_type*/15);
INSERT INTO `unit_background` VALUES (/*unit_id*/105601, /*unit_name*/'大刀洗流夏', /*bg_id*/500050, /*bg_name*/'兰德索尔 饮食店内', /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/105701, /*unit_name*/'姬塔', /*bg_id*/500200, /*bg_name*/'布里萨溪谷', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/105801, /*unit_name*/'佩可莉姆', /*bg_id*/500130, /*bg_name*/'埃斯特雷拉街道', /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/105901, /*unit_name*/'可可萝', /*bg_id*/500130, /*bg_name*/'埃斯特雷拉街道', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/106001, /*unit_name*/'凯露', /*bg_id*/500130, /*bg_name*/'埃斯特雷拉街道', /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/106101, /*unit_name*/'矛依未', /*bg_id*/500341, /*bg_name*/'拉比林斯公会据点', /*position*/0.0, /*face_type*/20);
INSERT INTO `unit_background` VALUES (/*unit_id*/106301, /*unit_name*/'亚里莎', /*bg_id*/500170, /*bg_name*/'神秘森林', /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/106801, /*unit_name*/'模索路晶', /*bg_id*/500030, /*bg_name*/'兰德索尔 繁华街', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/107101, /*unit_name*/'克里斯提娜·摩根', /*bg_id*/500090, /*bg_name*/'兰德索尔 王城入口', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/107501, /*unit_name*/'佩可莉姆（夏日）', /*bg_id*/500164, /*bg_name*/'马尔冈海岸', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/107601, /*unit_name*/'可可萝（夏日）', /*bg_id*/500164, /*bg_name*/'马尔冈海岸', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/107701, /*unit_name*/'铃莓（夏日）', /*bg_id*/500164, /*bg_name*/'马尔简海岸', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/107801, /*unit_name*/'凯露（夏日）', /*bg_id*/500164, /*bg_name*/'马尔简海岸', /*position*/0.0, /*face_type*/6);
INSERT INTO `unit_background` VALUES (/*unit_id*/107901, /*unit_name*/'珠希（夏日）', /*bg_id*/500284, /*bg_name*/'无人岛', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/108001, /*unit_name*/'美冬（夏日）', /*bg_id*/500284, /*bg_name*/'无人岛', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/108101, /*unit_name*/'忍（万圣节）', /*bg_id*/500264, /*bg_name*/'古城 万圣节', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108201, /*unit_name*/'宫子（万圣节）', /*bg_id*/500264, /*bg_name*/'古城 万圣节', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108301, /*unit_name*/'美咲（万圣节）', /*bg_id*/505030, /*bg_name*/'兰德索尔 闹市 万圣节', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/108401, /*unit_name*/'千歌（圣诞节）', /*bg_id*/500114, /*bg_name*/'咲恋救济院_大厅_圣诞节', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/108501, /*unit_name*/'胡桃（圣诞节）', /*bg_id*/500114, /*bg_name*/'咲恋救济院_大厅_圣诞节', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108601, /*unit_name*/'绫音（圣诞节）', /*bg_id*/500114, /*bg_name*/'咲恋救济院_大厅_圣诞节', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108701, /*unit_name*/'日和莉（新年）', /*bg_id*/500553, /*bg_name*/'新年神殿', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108801, /*unit_name*/'优衣（新年）', /*bg_id*/500553, /*bg_name*/'新年神殿', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108901, /*unit_name*/'怜（新年）', /*bg_id*/500553, /*bg_name*/'新年神殿', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/109001, /*unit_name*/'惠理子（情人节）', /*bg_id*/500600, /*bg_name*/'厨房竞技场', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/109101, /*unit_name*/'静流（情人节）', /*bg_id*/500600, /*bg_name*/'厨房竞技场', /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/109201, /*unit_name*/'安', /*bg_id*/500133, /*bg_name*/'埃斯特雷拉街道', /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/109301, /*unit_name*/'露', /*bg_id*/500133, /*bg_name*/'埃斯特雷拉街道', /*position*/0.0, /*face_type*/4);
